// Code generated by "stringer -type=EdgeType"; DO NOT EDIT

package depgraph

import "fmt"

const _EdgeType_name = "LibraryToLibraryLibraryToFileFileToLibraryFileToFileFileToSymbolLibraryToSymbolImplicitLibraryToLibraryArtifactToLibrary"

var _EdgeType_index = [...]uint8{0, 16, 29, 42, 52, 64, 79, 103, 120}

func (i EdgeType) String() string {
	i -= 1
	if i < 0 || i >= EdgeType(len(_EdgeType_index)-1) {
		return fmt.Sprintf("EdgeType(%d)", i+1)
	}
	return _EdgeType_name[_EdgeType_index[i]:_EdgeType_index[i+1]]
}
