// Code generated by "stringer -type=NodeType"; DO NOT EDIT

package depgraph

import "fmt"

const _NodeType_name = "LibrarySymbolFileArtifact"

var _NodeType_index = [...]uint8{0, 7, 13, 17, 25}

func (i NodeType) String() string {
	i -= 1
	if i < 0 || i >= NodeType(len(_NodeType_index)-1) {
		return fmt.Sprintf("NodeType(%d)", i+1)
	}
	return _NodeType_name[_NodeType_index[i]:_NodeType_index[i+1]]
}
