// Code generated by protoc-gen-go. DO NOT EDIT.
// source: buildlogger.proto

package internal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Format int32

const (
	Format_LOG_FORMAT_UNKNOWN Format = 0
	Format_LOG_FORMAT_TEXT    Format = 1
	Format_LOG_FORMAT_JSON    Format = 2
	Format_LOG_FORMAT_BSON    Format = 3
)

var Format_name = map[int32]string{
	0: "LOG_FORMAT_UNKNOWN",
	1: "LOG_FORMAT_TEXT",
	2: "LOG_FORMAT_JSON",
	3: "LOG_FORMAT_BSON",
}

var Format_value = map[string]int32{
	"LOG_FORMAT_UNKNOWN": 0,
	"LOG_FORMAT_TEXT":    1,
	"LOG_FORMAT_JSON":    2,
	"LOG_FORMAT_BSON":    3,
}

func (x Format) String() string {
	return proto.EnumName(Format_name, int32(x))
}

func (Format) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c4f5c52c3a3ee6d6, []int{0}
}

type LogInfo struct {
	Project              string               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Version              string               `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Variant              string               `protobuf:"bytes,3,opt,name=variant,proto3" json:"variant,omitempty"`
	TaskName             string               `protobuf:"bytes,4,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	TaskId               string               `protobuf:"bytes,5,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Execution            int32                `protobuf:"varint,6,opt,name=execution,proto3" json:"execution,omitempty"`
	TestName             string               `protobuf:"bytes,7,opt,name=test_name,json=testName,proto3" json:"test_name,omitempty"`
	Trial                int32                `protobuf:"varint,8,opt,name=trial,proto3" json:"trial,omitempty"`
	ProcName             string               `protobuf:"bytes,9,opt,name=proc_name,json=procName,proto3" json:"proc_name,omitempty"`
	Format               Format               `protobuf:"varint,10,opt,name=format,proto3,enum=cedar.Format" json:"format,omitempty"`
	Arguments            map[string]string    `protobuf:"bytes,11,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Mainline             bool                 `protobuf:"varint,12,opt,name=mainline,proto3" json:"mainline,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LogInfo) Reset()         { *m = LogInfo{} }
func (m *LogInfo) String() string { return proto.CompactTextString(m) }
func (*LogInfo) ProtoMessage()    {}
func (*LogInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f5c52c3a3ee6d6, []int{0}
}

func (m *LogInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogInfo.Unmarshal(m, b)
}
func (m *LogInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogInfo.Marshal(b, m, deterministic)
}
func (m *LogInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogInfo.Merge(m, src)
}
func (m *LogInfo) XXX_Size() int {
	return xxx_messageInfo_LogInfo.Size(m)
}
func (m *LogInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LogInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LogInfo proto.InternalMessageInfo

func (m *LogInfo) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *LogInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *LogInfo) GetVariant() string {
	if m != nil {
		return m.Variant
	}
	return ""
}

func (m *LogInfo) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *LogInfo) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *LogInfo) GetExecution() int32 {
	if m != nil {
		return m.Execution
	}
	return 0
}

func (m *LogInfo) GetTestName() string {
	if m != nil {
		return m.TestName
	}
	return ""
}

func (m *LogInfo) GetTrial() int32 {
	if m != nil {
		return m.Trial
	}
	return 0
}

func (m *LogInfo) GetProcName() string {
	if m != nil {
		return m.ProcName
	}
	return ""
}

func (m *LogInfo) GetFormat() Format {
	if m != nil {
		return m.Format
	}
	return Format_LOG_FORMAT_UNKNOWN
}

func (m *LogInfo) GetArguments() map[string]string {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *LogInfo) GetMainline() bool {
	if m != nil {
		return m.Mainline
	}
	return false
}

func (m *LogInfo) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type Loglines struct {
	Lines                []*LogLine `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Loglines) Reset()         { *m = Loglines{} }
func (m *Loglines) String() string { return proto.CompactTextString(m) }
func (*Loglines) ProtoMessage()    {}
func (*Loglines) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f5c52c3a3ee6d6, []int{1}
}

func (m *Loglines) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Loglines.Unmarshal(m, b)
}
func (m *Loglines) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Loglines.Marshal(b, m, deterministic)
}
func (m *Loglines) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Loglines.Merge(m, src)
}
func (m *Loglines) XXX_Size() int {
	return xxx_messageInfo_Loglines.Size(m)
}
func (m *Loglines) XXX_DiscardUnknown() {
	xxx_messageInfo_Loglines.DiscardUnknown(m)
}

var xxx_messageInfo_Loglines proto.InternalMessageInfo

func (m *Loglines) GetLines() []*LogLine {
	if m != nil {
		return m.Lines
	}
	return nil
}

type LogLine struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data                 string               `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LogLine) Reset()         { *m = LogLine{} }
func (m *LogLine) String() string { return proto.CompactTextString(m) }
func (*LogLine) ProtoMessage()    {}
func (*LogLine) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f5c52c3a3ee6d6, []int{2}
}

func (m *LogLine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogLine.Unmarshal(m, b)
}
func (m *LogLine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogLine.Marshal(b, m, deterministic)
}
func (m *LogLine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogLine.Merge(m, src)
}
func (m *LogLine) XXX_Size() int {
	return xxx_messageInfo_LogLine.Size(m)
}
func (m *LogLine) XXX_DiscardUnknown() {
	xxx_messageInfo_LogLine.DiscardUnknown(m)
}

var xxx_messageInfo_LogLine proto.InternalMessageInfo

func (m *LogLine) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *LogLine) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type LogEndInfo struct {
	ExitCode             int32                `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	CompletedAt          *timestamp.Timestamp `protobuf:"bytes,2,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LogEndInfo) Reset()         { *m = LogEndInfo{} }
func (m *LogEndInfo) String() string { return proto.CompactTextString(m) }
func (*LogEndInfo) ProtoMessage()    {}
func (*LogEndInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f5c52c3a3ee6d6, []int{3}
}

func (m *LogEndInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEndInfo.Unmarshal(m, b)
}
func (m *LogEndInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEndInfo.Marshal(b, m, deterministic)
}
func (m *LogEndInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEndInfo.Merge(m, src)
}
func (m *LogEndInfo) XXX_Size() int {
	return xxx_messageInfo_LogEndInfo.Size(m)
}
func (m *LogEndInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEndInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LogEndInfo proto.InternalMessageInfo

func (m *LogEndInfo) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *LogEndInfo) GetCompletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CompletedAt
	}
	return nil
}

func init() {
	proto.RegisterEnum("cedar.Format", Format_name, Format_value)
	proto.RegisterType((*LogInfo)(nil), "cedar.LogInfo")
	proto.RegisterMapType((map[string]string)(nil), "cedar.LogInfo.ArgumentsEntry")
	proto.RegisterType((*Loglines)(nil), "cedar.Loglines")
	proto.RegisterType((*LogLine)(nil), "cedar.LogLine")
	proto.RegisterType((*LogEndInfo)(nil), "cedar.LogEndInfo")
}

func init() { proto.RegisterFile("buildlogger.proto", fileDescriptor_c4f5c52c3a3ee6d6) }

var fileDescriptor_c4f5c52c3a3ee6d6 = []byte{
	// 528 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x25, 0xed, 0xd2, 0x26, 0xb7, 0xdb, 0x28, 0x06, 0x81, 0xd5, 0x81, 0x88, 0x2a, 0x90, 0x22,
	0x1e, 0x32, 0x34, 0x5e, 0xc6, 0xd7, 0x43, 0x87, 0x36, 0x34, 0x28, 0xad, 0x14, 0x8a, 0x86, 0x78,
	0x89, 0xdc, 0xe4, 0x36, 0x84, 0x25, 0x76, 0xe5, 0xb8, 0x13, 0xfb, 0xdf, 0xfc, 0x00, 0x64, 0xc7,
	0x6d, 0x61, 0x2f, 0x7b, 0xf3, 0x39, 0xe7, 0x7e, 0xf9, 0x9e, 0x0b, 0xf7, 0xe6, 0xab, 0xa2, 0xcc,
	0x4a, 0x91, 0xe7, 0x28, 0xa3, 0xa5, 0x14, 0x4a, 0x10, 0x37, 0xc5, 0x8c, 0xc9, 0xc1, 0xd3, 0x5c,
	0x88, 0xbc, 0xc4, 0x43, 0x43, 0xce, 0x57, 0x8b, 0x43, 0x55, 0x54, 0x58, 0x2b, 0x56, 0x2d, 0x9b,
	0xb8, 0xe1, 0x9f, 0x36, 0x74, 0xc7, 0x22, 0x3f, 0xe7, 0x0b, 0x41, 0x28, 0x74, 0x97, 0x52, 0xfc,
	0xc2, 0x54, 0x51, 0x27, 0x70, 0x42, 0x3f, 0x5e, 0x43, 0xad, 0x5c, 0xa1, 0xac, 0x0b, 0xc1, 0x69,
	0xab, 0x51, 0x2c, 0x34, 0x0a, 0x93, 0x05, 0xe3, 0x8a, 0xb6, 0xad, 0xd2, 0x40, 0x72, 0x00, 0xbe,
	0x62, 0xf5, 0x65, 0xc2, 0x59, 0x85, 0x74, 0xc7, 0x68, 0x9e, 0x26, 0x26, 0xac, 0x42, 0xf2, 0x08,
	0xba, 0x46, 0x2c, 0x32, 0xea, 0x1a, 0xa9, 0xa3, 0xe1, 0x79, 0x46, 0x1e, 0x83, 0x8f, 0xbf, 0x31,
	0x5d, 0x29, 0xdd, 0xab, 0x13, 0x38, 0xa1, 0x1b, 0x6f, 0x09, 0x53, 0x13, 0x6b, 0xd5, 0xd4, 0xec,
	0xda, 0x9a, 0x58, 0x2b, 0x53, 0xf3, 0x01, 0xb8, 0x4a, 0x16, 0xac, 0xa4, 0x9e, 0x49, 0x6b, 0x80,
	0x4e, 0x59, 0x4a, 0x91, 0x36, 0x29, 0x7e, 0x93, 0xa2, 0x09, 0x93, 0xf2, 0x1c, 0x3a, 0x0b, 0x21,
	0x2b, 0xa6, 0x28, 0x04, 0x4e, 0xb8, 0x7f, 0xb4, 0x17, 0x99, 0xb5, 0x45, 0x67, 0x86, 0x8c, 0xad,
	0x48, 0xde, 0x82, 0xcf, 0x64, 0xbe, 0xaa, 0x90, 0xab, 0x9a, 0xf6, 0x82, 0x76, 0xd8, 0x3b, 0x7a,
	0x62, 0x23, 0xed, 0xee, 0xa2, 0xd1, 0x5a, 0x3f, 0xe5, 0x4a, 0x5e, 0xc7, 0xdb, 0x78, 0x32, 0x00,
	0xaf, 0x62, 0x05, 0x2f, 0x0b, 0x8e, 0x74, 0x37, 0x70, 0x42, 0x2f, 0xde, 0x60, 0xf2, 0x1a, 0x20,
	0x95, 0xc8, 0x14, 0x66, 0x09, 0x53, 0x74, 0x2f, 0x70, 0xc2, 0xde, 0xd1, 0x20, 0x6a, 0x3c, 0x8b,
	0xd6, 0x9e, 0x45, 0xb3, 0xb5, 0x67, 0xb1, 0x6f, 0xa3, 0x47, 0x6a, 0xf0, 0x0e, 0xf6, 0xff, 0xef,
	0x49, 0xfa, 0xd0, 0xbe, 0xc4, 0x6b, 0x6b, 0x9d, 0x7e, 0xea, 0x8d, 0x5c, 0xb1, 0x72, 0x85, 0xd6,
	0xb4, 0x06, 0xbc, 0x69, 0x1d, 0x3b, 0xc3, 0x97, 0xe0, 0x8d, 0x45, 0xae, 0x67, 0xa8, 0xc9, 0x33,
	0x70, 0xcd, 0x83, 0x3a, 0xe6, 0x67, 0xfb, 0xdb, 0x9f, 0x8d, 0x0b, 0x8e, 0x71, 0x23, 0x0e, 0x2f,
	0xcc, 0x9d, 0x68, 0x86, 0x1c, 0x83, 0xbf, 0x39, 0x23, 0xd3, 0xee, 0x96, 0xa1, 0x37, 0xc1, 0x84,
	0xc0, 0x4e, 0xc6, 0x14, 0xb3, 0xf3, 0x98, 0xf7, 0xf0, 0x27, 0xc0, 0x58, 0xe4, 0xa7, 0x3c, 0x33,
	0x37, 0x78, 0xa0, 0xfd, 0x2f, 0x54, 0x92, 0x8a, 0x0c, 0x4d, 0x6d, 0x37, 0xf6, 0x34, 0xf1, 0x41,
	0x64, 0x48, 0xde, 0xc3, 0x6e, 0x2a, 0xaa, 0x65, 0x89, 0x76, 0x61, 0xad, 0x5b, 0x7b, 0xf7, 0x36,
	0xf1, 0x23, 0xf5, 0x22, 0x81, 0x4e, 0x63, 0x2c, 0x79, 0x08, 0x64, 0x3c, 0xfd, 0x98, 0x9c, 0x4d,
	0xe3, 0x2f, 0xa3, 0x59, 0xf2, 0x6d, 0xf2, 0x79, 0x32, 0xbd, 0x98, 0xf4, 0xef, 0x90, 0xfb, 0x70,
	0xf7, 0x1f, 0x7e, 0x76, 0xfa, 0x7d, 0xd6, 0x77, 0x6e, 0x90, 0x9f, 0xbe, 0x4e, 0x27, 0xfd, 0xd6,
	0x0d, 0xf2, 0x44, 0x93, 0xed, 0x13, 0xf8, 0xe1, 0x15, 0x5c, 0xa1, 0xe4, 0xac, 0x9c, 0x77, 0xcc,
	0x34, 0xaf, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x19, 0x4a, 0x38, 0xd8, 0x9c, 0x03, 0x00, 0x00,
}
