// Code generated by protoc-gen-go. DO NOT EDIT.
// source: perf.proto

package internal

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StorageLocation int32

const (
	StorageLocation_UNKNOWN    StorageLocation = 0
	StorageLocation_SINK_S3    StorageLocation = 1
	StorageLocation_PROJECT_S3 StorageLocation = 2
	StorageLocation_GRIDFS     StorageLocation = 3
	StorageLocation_EPHEMERAL  StorageLocation = 4
)

var StorageLocation_name = map[int32]string{
	0: "UNKNOWN",
	1: "SINK_S3",
	2: "PROJECT_S3",
	3: "GRIDFS",
	4: "EPHEMERAL",
}

var StorageLocation_value = map[string]int32{
	"UNKNOWN":    0,
	"SINK_S3":    1,
	"PROJECT_S3": 2,
	"GRIDFS":     3,
	"EPHEMERAL":  4,
}

func (x StorageLocation) String() string {
	return proto.EnumName(StorageLocation_name, int32(x))
}

func (StorageLocation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0c323b185c5dcff5, []int{0}
}

type DataFormat int32

const (
	DataFormat_TEXT DataFormat = 0
	DataFormat_FTDC DataFormat = 1
	DataFormat_BSON DataFormat = 2
	DataFormat_JSON DataFormat = 3
	DataFormat_CSV  DataFormat = 4
)

var DataFormat_name = map[int32]string{
	0: "TEXT",
	1: "FTDC",
	2: "BSON",
	3: "JSON",
	4: "CSV",
}

var DataFormat_value = map[string]int32{
	"TEXT": 0,
	"FTDC": 1,
	"BSON": 2,
	"JSON": 3,
	"CSV":  4,
}

func (x DataFormat) String() string {
	return proto.EnumName(DataFormat_name, int32(x))
}

func (DataFormat) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0c323b185c5dcff5, []int{1}
}

type CompressionType int32

const (
	CompressionType_NONE  CompressionType = 0
	CompressionType_TARGZ CompressionType = 1
	CompressionType_ZIP   CompressionType = 2
	CompressionType_GZ    CompressionType = 3
	CompressionType_XZ    CompressionType = 4
)

var CompressionType_name = map[int32]string{
	0: "NONE",
	1: "TARGZ",
	2: "ZIP",
	3: "GZ",
	4: "XZ",
}

var CompressionType_value = map[string]int32{
	"NONE":  0,
	"TARGZ": 1,
	"ZIP":   2,
	"GZ":    3,
	"XZ":    4,
}

func (x CompressionType) String() string {
	return proto.EnumName(CompressionType_name, int32(x))
}

func (CompressionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0c323b185c5dcff5, []int{2}
}

type ResultID struct {
	Project              string           `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Version              string           `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	TaskName             string           `protobuf:"bytes,3,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	Execution            int32            `protobuf:"varint,4,opt,name=execution,proto3" json:"execution,omitempty"`
	TaskId               string           `protobuf:"bytes,5,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TestName             string           `protobuf:"bytes,6,opt,name=test_name,json=testName,proto3" json:"test_name,omitempty"`
	Parent               string           `protobuf:"bytes,7,opt,name=parent,proto3" json:"parent,omitempty"`
	Trial                int32            `protobuf:"varint,8,opt,name=trial,proto3" json:"trial,omitempty"`
	Tags                 []string         `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	Arguments            map[string]int32 `protobuf:"bytes,10,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Schema               int32            `protobuf:"varint,11,opt,name=schema,proto3" json:"schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ResultID) Reset()         { *m = ResultID{} }
func (m *ResultID) String() string { return proto.CompactTextString(m) }
func (*ResultID) ProtoMessage()    {}
func (*ResultID) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c323b185c5dcff5, []int{0}
}

func (m *ResultID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultID.Unmarshal(m, b)
}
func (m *ResultID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultID.Marshal(b, m, deterministic)
}
func (m *ResultID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultID.Merge(m, src)
}
func (m *ResultID) XXX_Size() int {
	return xxx_messageInfo_ResultID.Size(m)
}
func (m *ResultID) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultID.DiscardUnknown(m)
}

var xxx_messageInfo_ResultID proto.InternalMessageInfo

func (m *ResultID) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *ResultID) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ResultID) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *ResultID) GetExecution() int32 {
	if m != nil {
		return m.Execution
	}
	return 0
}

func (m *ResultID) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *ResultID) GetTestName() string {
	if m != nil {
		return m.TestName
	}
	return ""
}

func (m *ResultID) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ResultID) GetTrial() int32 {
	if m != nil {
		return m.Trial
	}
	return 0
}

func (m *ResultID) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ResultID) GetArguments() map[string]int32 {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *ResultID) GetSchema() int32 {
	if m != nil {
		return m.Schema
	}
	return 0
}

type ResultData struct {
	Id                   *ResultID       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Artifacts            []*ArtifactInfo `protobuf:"bytes,2,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	Rollups              *Rollups        `protobuf:"bytes,3,opt,name=rollups,proto3" json:"rollups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ResultData) Reset()         { *m = ResultData{} }
func (m *ResultData) String() string { return proto.CompactTextString(m) }
func (*ResultData) ProtoMessage()    {}
func (*ResultData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c323b185c5dcff5, []int{1}
}

func (m *ResultData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultData.Unmarshal(m, b)
}
func (m *ResultData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultData.Marshal(b, m, deterministic)
}
func (m *ResultData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultData.Merge(m, src)
}
func (m *ResultData) XXX_Size() int {
	return xxx_messageInfo_ResultData.Size(m)
}
func (m *ResultData) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultData.DiscardUnknown(m)
}

var xxx_messageInfo_ResultData proto.InternalMessageInfo

func (m *ResultData) GetId() *ResultID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ResultData) GetArtifacts() []*ArtifactInfo {
	if m != nil {
		return m.Artifacts
	}
	return nil
}

func (m *ResultData) GetRollups() *Rollups {
	if m != nil {
		return m.Rollups
	}
	return nil
}

type ArtifactInfo struct {
	Location             StorageLocation `protobuf:"varint,1,opt,name=location,proto3,enum=sink.StorageLocation" json:"location,omitempty"`
	Bucket               string          `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Path                 string          `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Format               DataFormat      `protobuf:"varint,4,opt,name=format,proto3,enum=sink.DataFormat" json:"format,omitempty"`
	Compression          CompressionType `protobuf:"varint,5,opt,name=compression,proto3,enum=sink.CompressionType" json:"compression,omitempty"`
	Tags                 []string        `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ArtifactInfo) Reset()         { *m = ArtifactInfo{} }
func (m *ArtifactInfo) String() string { return proto.CompactTextString(m) }
func (*ArtifactInfo) ProtoMessage()    {}
func (*ArtifactInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c323b185c5dcff5, []int{2}
}

func (m *ArtifactInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArtifactInfo.Unmarshal(m, b)
}
func (m *ArtifactInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArtifactInfo.Marshal(b, m, deterministic)
}
func (m *ArtifactInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArtifactInfo.Merge(m, src)
}
func (m *ArtifactInfo) XXX_Size() int {
	return xxx_messageInfo_ArtifactInfo.Size(m)
}
func (m *ArtifactInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ArtifactInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ArtifactInfo proto.InternalMessageInfo

func (m *ArtifactInfo) GetLocation() StorageLocation {
	if m != nil {
		return m.Location
	}
	return StorageLocation_UNKNOWN
}

func (m *ArtifactInfo) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *ArtifactInfo) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ArtifactInfo) GetFormat() DataFormat {
	if m != nil {
		return m.Format
	}
	return DataFormat_TEXT
}

func (m *ArtifactInfo) GetCompression() CompressionType {
	if m != nil {
		return m.Compression
	}
	return CompressionType_NONE
}

func (m *ArtifactInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type MetricsSeriesEnd struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsComplete           bool     `protobuf:"varint,2,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetricsSeriesEnd) Reset()         { *m = MetricsSeriesEnd{} }
func (m *MetricsSeriesEnd) String() string { return proto.CompactTextString(m) }
func (*MetricsSeriesEnd) ProtoMessage()    {}
func (*MetricsSeriesEnd) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c323b185c5dcff5, []int{3}
}

func (m *MetricsSeriesEnd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsSeriesEnd.Unmarshal(m, b)
}
func (m *MetricsSeriesEnd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsSeriesEnd.Marshal(b, m, deterministic)
}
func (m *MetricsSeriesEnd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsSeriesEnd.Merge(m, src)
}
func (m *MetricsSeriesEnd) XXX_Size() int {
	return xxx_messageInfo_MetricsSeriesEnd.Size(m)
}
func (m *MetricsSeriesEnd) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsSeriesEnd.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsSeriesEnd proto.InternalMessageInfo

func (m *MetricsSeriesEnd) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MetricsSeriesEnd) GetIsComplete() bool {
	if m != nil {
		return m.IsComplete
	}
	return false
}

type MetricsResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetricsResponse) Reset()         { *m = MetricsResponse{} }
func (m *MetricsResponse) String() string { return proto.CompactTextString(m) }
func (*MetricsResponse) ProtoMessage()    {}
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c323b185c5dcff5, []int{4}
}

func (m *MetricsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsResponse.Unmarshal(m, b)
}
func (m *MetricsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsResponse.Marshal(b, m, deterministic)
}
func (m *MetricsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsResponse.Merge(m, src)
}
func (m *MetricsResponse) XXX_Size() int {
	return xxx_messageInfo_MetricsResponse.Size(m)
}
func (m *MetricsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsResponse proto.InternalMessageInfo

func (m *MetricsResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MetricsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type SendResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Count                int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendResponse) Reset()         { *m = SendResponse{} }
func (m *SendResponse) String() string { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()    {}
func (*SendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c323b185c5dcff5, []int{5}
}

func (m *SendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResponse.Unmarshal(m, b)
}
func (m *SendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResponse.Marshal(b, m, deterministic)
}
func (m *SendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResponse.Merge(m, src)
}
func (m *SendResponse) XXX_Size() int {
	return xxx_messageInfo_SendResponse.Size(m)
}
func (m *SendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendResponse proto.InternalMessageInfo

func (m *SendResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SendResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SendResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type MetricsPoint struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=Time,proto3" json:"Time,omitempty"`
	Counters             *MetricsCounters     `protobuf:"bytes,2,opt,name=counters,proto3" json:"counters,omitempty"`
	Timers               *MetricsTimers       `protobuf:"bytes,3,opt,name=timers,proto3" json:"timers,omitempty"`
	Guages               *MetricsGuages       `protobuf:"bytes,4,opt,name=guages,proto3" json:"guages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MetricsPoint) Reset()         { *m = MetricsPoint{} }
func (m *MetricsPoint) String() string { return proto.CompactTextString(m) }
func (*MetricsPoint) ProtoMessage()    {}
func (*MetricsPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c323b185c5dcff5, []int{6}
}

func (m *MetricsPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsPoint.Unmarshal(m, b)
}
func (m *MetricsPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsPoint.Marshal(b, m, deterministic)
}
func (m *MetricsPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsPoint.Merge(m, src)
}
func (m *MetricsPoint) XXX_Size() int {
	return xxx_messageInfo_MetricsPoint.Size(m)
}
func (m *MetricsPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsPoint.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsPoint proto.InternalMessageInfo

func (m *MetricsPoint) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *MetricsPoint) GetCounters() *MetricsCounters {
	if m != nil {
		return m.Counters
	}
	return nil
}

func (m *MetricsPoint) GetTimers() *MetricsTimers {
	if m != nil {
		return m.Timers
	}
	return nil
}

func (m *MetricsPoint) GetGuages() *MetricsGuages {
	if m != nil {
		return m.Guages
	}
	return nil
}

type MetricsCounters struct {
	Ops                  int64    `protobuf:"varint,1,opt,name=ops,proto3" json:"ops,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Errors               int64    `protobuf:"varint,3,opt,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetricsCounters) Reset()         { *m = MetricsCounters{} }
func (m *MetricsCounters) String() string { return proto.CompactTextString(m) }
func (*MetricsCounters) ProtoMessage()    {}
func (*MetricsCounters) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c323b185c5dcff5, []int{7}
}

func (m *MetricsCounters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsCounters.Unmarshal(m, b)
}
func (m *MetricsCounters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsCounters.Marshal(b, m, deterministic)
}
func (m *MetricsCounters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsCounters.Merge(m, src)
}
func (m *MetricsCounters) XXX_Size() int {
	return xxx_messageInfo_MetricsCounters.Size(m)
}
func (m *MetricsCounters) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsCounters.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsCounters proto.InternalMessageInfo

func (m *MetricsCounters) GetOps() int64 {
	if m != nil {
		return m.Ops
	}
	return 0
}

func (m *MetricsCounters) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *MetricsCounters) GetErrors() int64 {
	if m != nil {
		return m.Errors
	}
	return 0
}

type MetricsTimers struct {
	Duration             *duration.Duration `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`
	Total                *duration.Duration `protobuf:"bytes,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MetricsTimers) Reset()         { *m = MetricsTimers{} }
func (m *MetricsTimers) String() string { return proto.CompactTextString(m) }
func (*MetricsTimers) ProtoMessage()    {}
func (*MetricsTimers) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c323b185c5dcff5, []int{8}
}

func (m *MetricsTimers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsTimers.Unmarshal(m, b)
}
func (m *MetricsTimers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsTimers.Marshal(b, m, deterministic)
}
func (m *MetricsTimers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsTimers.Merge(m, src)
}
func (m *MetricsTimers) XXX_Size() int {
	return xxx_messageInfo_MetricsTimers.Size(m)
}
func (m *MetricsTimers) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsTimers.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsTimers proto.InternalMessageInfo

func (m *MetricsTimers) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *MetricsTimers) GetTotal() *duration.Duration {
	if m != nil {
		return m.Total
	}
	return nil
}

type MetricsGuages struct {
	State                int64    `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	Workers              int64    `protobuf:"varint,2,opt,name=workers,proto3" json:"workers,omitempty"`
	Failed               bool     `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetricsGuages) Reset()         { *m = MetricsGuages{} }
func (m *MetricsGuages) String() string { return proto.CompactTextString(m) }
func (*MetricsGuages) ProtoMessage()    {}
func (*MetricsGuages) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c323b185c5dcff5, []int{9}
}

func (m *MetricsGuages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsGuages.Unmarshal(m, b)
}
func (m *MetricsGuages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsGuages.Marshal(b, m, deterministic)
}
func (m *MetricsGuages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsGuages.Merge(m, src)
}
func (m *MetricsGuages) XXX_Size() int {
	return xxx_messageInfo_MetricsGuages.Size(m)
}
func (m *MetricsGuages) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsGuages.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsGuages proto.InternalMessageInfo

func (m *MetricsGuages) GetState() int64 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *MetricsGuages) GetWorkers() int64 {
	if m != nil {
		return m.Workers
	}
	return 0
}

func (m *MetricsGuages) GetFailed() bool {
	if m != nil {
		return m.Failed
	}
	return false
}

type MetricsEvent struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Event                []*MetricsPoint `protobuf:"bytes,3,rep,name=Event,proto3" json:"Event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MetricsEvent) Reset()         { *m = MetricsEvent{} }
func (m *MetricsEvent) String() string { return proto.CompactTextString(m) }
func (*MetricsEvent) ProtoMessage()    {}
func (*MetricsEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c323b185c5dcff5, []int{10}
}

func (m *MetricsEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsEvent.Unmarshal(m, b)
}
func (m *MetricsEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsEvent.Marshal(b, m, deterministic)
}
func (m *MetricsEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsEvent.Merge(m, src)
}
func (m *MetricsEvent) XXX_Size() int {
	return xxx_messageInfo_MetricsEvent.Size(m)
}
func (m *MetricsEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsEvent.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsEvent proto.InternalMessageInfo

func (m *MetricsEvent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MetricsEvent) GetEvent() []*MetricsPoint {
	if m != nil {
		return m.Event
	}
	return nil
}

type RollupValue struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*RollupValue_Int
	//	*RollupValue_Fl
	Value                isRollupValue_Value `protobuf_oneof:"value"`
	Version              int64               `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RollupValue) Reset()         { *m = RollupValue{} }
func (m *RollupValue) String() string { return proto.CompactTextString(m) }
func (*RollupValue) ProtoMessage()    {}
func (*RollupValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c323b185c5dcff5, []int{11}
}

func (m *RollupValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollupValue.Unmarshal(m, b)
}
func (m *RollupValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollupValue.Marshal(b, m, deterministic)
}
func (m *RollupValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollupValue.Merge(m, src)
}
func (m *RollupValue) XXX_Size() int {
	return xxx_messageInfo_RollupValue.Size(m)
}
func (m *RollupValue) XXX_DiscardUnknown() {
	xxx_messageInfo_RollupValue.DiscardUnknown(m)
}

var xxx_messageInfo_RollupValue proto.InternalMessageInfo

func (m *RollupValue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isRollupValue_Value interface {
	isRollupValue_Value()
}

type RollupValue_Int struct {
	Int int64 `protobuf:"varint,2,opt,name=int,proto3,oneof"`
}

type RollupValue_Fl struct {
	Fl float32 `protobuf:"fixed32,3,opt,name=fl,proto3,oneof"`
}

func (*RollupValue_Int) isRollupValue_Value() {}

func (*RollupValue_Fl) isRollupValue_Value() {}

func (m *RollupValue) GetValue() isRollupValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *RollupValue) GetInt() int64 {
	if x, ok := m.GetValue().(*RollupValue_Int); ok {
		return x.Int
	}
	return 0
}

func (m *RollupValue) GetFl() float32 {
	if x, ok := m.GetValue().(*RollupValue_Fl); ok {
		return x.Fl
	}
	return 0
}

func (m *RollupValue) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RollupValue) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RollupValue_OneofMarshaler, _RollupValue_OneofUnmarshaler, _RollupValue_OneofSizer, []interface{}{
		(*RollupValue_Int)(nil),
		(*RollupValue_Fl)(nil),
	}
}

func _RollupValue_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RollupValue)
	// value
	switch x := m.Value.(type) {
	case *RollupValue_Int:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Int))
	case *RollupValue_Fl:
		b.EncodeVarint(3<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.Fl)))
	case nil:
	default:
		return fmt.Errorf("RollupValue.Value has unexpected type %T", x)
	}
	return nil
}

func _RollupValue_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RollupValue)
	switch tag {
	case 2: // value.int
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &RollupValue_Int{int64(x)}
		return true, err
	case 3: // value.fl
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Value = &RollupValue_Fl{math.Float32frombits(uint32(x))}
		return true, err
	default:
		return false, nil
	}
}

func _RollupValue_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RollupValue)
	// value
	switch x := m.Value.(type) {
	case *RollupValue_Int:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Int))
	case *RollupValue_Fl:
		n += 1 // tag and wire
		n += 4
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Rollups struct {
	DefaultStats         []*RollupValue       `protobuf:"bytes,1,rep,name=default_stats,json=defaultStats,proto3" json:"default_stats,omitempty"`
	UserStats            []*RollupValue       `protobuf:"bytes,2,rep,name=user_stats,json=userStats,proto3" json:"user_stats,omitempty"`
	ProcessedAt          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	Count                int64                `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Valid                bool                 `protobuf:"varint,5,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Rollups) Reset()         { *m = Rollups{} }
func (m *Rollups) String() string { return proto.CompactTextString(m) }
func (*Rollups) ProtoMessage()    {}
func (*Rollups) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c323b185c5dcff5, []int{12}
}

func (m *Rollups) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rollups.Unmarshal(m, b)
}
func (m *Rollups) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rollups.Marshal(b, m, deterministic)
}
func (m *Rollups) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rollups.Merge(m, src)
}
func (m *Rollups) XXX_Size() int {
	return xxx_messageInfo_Rollups.Size(m)
}
func (m *Rollups) XXX_DiscardUnknown() {
	xxx_messageInfo_Rollups.DiscardUnknown(m)
}

var xxx_messageInfo_Rollups proto.InternalMessageInfo

func (m *Rollups) GetDefaultStats() []*RollupValue {
	if m != nil {
		return m.DefaultStats
	}
	return nil
}

func (m *Rollups) GetUserStats() []*RollupValue {
	if m != nil {
		return m.UserStats
	}
	return nil
}

func (m *Rollups) GetProcessedAt() *timestamp.Timestamp {
	if m != nil {
		return m.ProcessedAt
	}
	return nil
}

func (m *Rollups) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Rollups) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterEnum("sink.StorageLocation", StorageLocation_name, StorageLocation_value)
	proto.RegisterEnum("sink.DataFormat", DataFormat_name, DataFormat_value)
	proto.RegisterEnum("sink.CompressionType", CompressionType_name, CompressionType_value)
	proto.RegisterType((*ResultID)(nil), "sink.ResultID")
	proto.RegisterMapType((map[string]int32)(nil), "sink.ResultID.ArgumentsEntry")
	proto.RegisterType((*ResultData)(nil), "sink.ResultData")
	proto.RegisterType((*ArtifactInfo)(nil), "sink.ArtifactInfo")
	proto.RegisterType((*MetricsSeriesEnd)(nil), "sink.MetricsSeriesEnd")
	proto.RegisterType((*MetricsResponse)(nil), "sink.MetricsResponse")
	proto.RegisterType((*SendResponse)(nil), "sink.SendResponse")
	proto.RegisterType((*MetricsPoint)(nil), "sink.MetricsPoint")
	proto.RegisterType((*MetricsCounters)(nil), "sink.MetricsCounters")
	proto.RegisterType((*MetricsTimers)(nil), "sink.MetricsTimers")
	proto.RegisterType((*MetricsGuages)(nil), "sink.MetricsGuages")
	proto.RegisterType((*MetricsEvent)(nil), "sink.MetricsEvent")
	proto.RegisterType((*RollupValue)(nil), "sink.RollupValue")
	proto.RegisterType((*Rollups)(nil), "sink.Rollups")
}

func init() { proto.RegisterFile("perf.proto", fileDescriptor_0c323b185c5dcff5) }

var fileDescriptor_0c323b185c5dcff5 = []byte{
	// 1183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0x36, 0x49, 0x1d, 0x47, 0xb6, 0xcc, 0x7f, 0xff, 0x36, 0x65, 0xd5, 0x36, 0x31, 0x78, 0x53,
	0x21, 0x05, 0x94, 0x54, 0x41, 0x9b, 0x20, 0x69, 0x50, 0x28, 0xb2, 0x62, 0x2b, 0x07, 0xd9, 0x58,
	0xa9, 0x4e, 0xe0, 0x1b, 0x63, 0x4d, 0xad, 0x64, 0x46, 0x14, 0x49, 0xec, 0x2e, 0x9d, 0xba, 0x97,
	0x45, 0x81, 0x3e, 0x5c, 0xdf, 0xa1, 0x57, 0x7d, 0x90, 0x62, 0x0f, 0xa4, 0x24, 0x07, 0x09, 0xdc,
	0x2b, 0xee, 0xec, 0x7c, 0x33, 0x3b, 0xfb, 0xcd, 0xec, 0x47, 0x80, 0x94, 0xb2, 0x59, 0x27, 0x65,
	0x89, 0x48, 0x50, 0x89, 0x87, 0xf1, 0xa2, 0x75, 0x7b, 0x9e, 0x24, 0xf3, 0x88, 0xde, 0x53, 0x7b,
	0xe7, 0xd9, 0xec, 0xde, 0x34, 0x63, 0x44, 0x84, 0x49, 0xac, 0x51, 0xad, 0x3b, 0xd7, 0xfd, 0x22,
	0x5c, 0x52, 0x2e, 0xc8, 0x32, 0xd5, 0x00, 0xff, 0x0f, 0x07, 0x6a, 0x98, 0xf2, 0x2c, 0x12, 0xc3,
	0x7d, 0xe4, 0x41, 0x35, 0x65, 0xc9, 0x3b, 0x1a, 0x08, 0xcf, 0xda, 0xb3, 0xda, 0x75, 0x9c, 0x9b,
	0xd2, 0x73, 0x49, 0x19, 0x0f, 0x93, 0xd8, 0xb3, 0xb5, 0xc7, 0x98, 0xe8, 0x2b, 0xa8, 0x0b, 0xc2,
	0x17, 0x67, 0x31, 0x59, 0x52, 0xcf, 0x51, 0xbe, 0x9a, 0xdc, 0x18, 0x91, 0x25, 0x45, 0x5f, 0x43,
	0x9d, 0xfe, 0x4a, 0x83, 0x4c, 0x56, 0xe4, 0x95, 0xf6, 0xac, 0x76, 0x19, 0xaf, 0x36, 0xd0, 0x17,
	0x50, 0x55, 0xa1, 0xe1, 0xd4, 0x2b, 0xab, 0xc0, 0x8a, 0x34, 0x87, 0x53, 0x95, 0x93, 0x72, 0xa1,
	0x73, 0x56, 0x4c, 0x4e, 0xca, 0x85, 0xca, 0x79, 0x0b, 0x2a, 0x29, 0x61, 0x34, 0x16, 0x5e, 0x55,
	0x07, 0x69, 0x0b, 0x7d, 0x06, 0x65, 0xc1, 0x42, 0x12, 0x79, 0x35, 0x75, 0x8e, 0x36, 0x10, 0x82,
	0x92, 0x20, 0x73, 0xee, 0xd5, 0xf7, 0x9c, 0x76, 0x1d, 0xab, 0x35, 0x7a, 0x02, 0x75, 0xc2, 0xe6,
	0xd9, 0x92, 0xc6, 0x82, 0x7b, 0xb0, 0xe7, 0xb4, 0x1b, 0xdd, 0x6f, 0x3a, 0x92, 0xce, 0x4e, 0xce,
	0x44, 0xa7, 0x97, 0xfb, 0x07, 0xb1, 0x60, 0x57, 0x78, 0x85, 0x97, 0xc7, 0xf3, 0xe0, 0x82, 0x2e,
	0x89, 0xd7, 0x50, 0xe7, 0x18, 0xab, 0xf5, 0x13, 0x34, 0x37, 0x83, 0x90, 0x0b, 0xce, 0x82, 0x5e,
	0x19, 0x26, 0xe5, 0x52, 0x96, 0x78, 0x49, 0xa2, 0x8c, 0x2a, 0x0e, 0xcb, 0x58, 0x1b, 0x8f, 0xed,
	0x47, 0x96, 0xff, 0xa7, 0x05, 0xa0, 0x0f, 0xdf, 0x27, 0x82, 0xa0, 0xdb, 0x60, 0x87, 0x53, 0x15,
	0xd9, 0xe8, 0x36, 0x37, 0x4b, 0xc3, 0x76, 0x38, 0x45, 0xf7, 0xe5, 0x0d, 0x44, 0x38, 0x23, 0x81,
	0xe0, 0x9e, 0xad, 0x6e, 0x80, 0x34, 0xac, 0x67, 0xb6, 0x87, 0xf1, 0x2c, 0xc1, 0x2b, 0x10, 0xfa,
	0x16, 0xaa, 0x2c, 0x89, 0xa2, 0x2c, 0xe5, 0xaa, 0x49, 0x8d, 0xee, 0x8e, 0x49, 0xab, 0x37, 0x71,
	0xee, 0xf5, 0xff, 0xb1, 0x60, 0x7b, 0x3d, 0x09, 0xfa, 0x1e, 0x6a, 0x51, 0x12, 0xa8, 0xa1, 0x52,
	0x15, 0x35, 0xbb, 0x9f, 0xeb, 0xd0, 0xb1, 0x48, 0x18, 0x99, 0xd3, 0x57, 0xc6, 0x89, 0x0b, 0x98,
	0xe4, 0xe8, 0x3c, 0x0b, 0x16, 0x54, 0x98, 0x61, 0x31, 0x96, 0x6c, 0x46, 0x4a, 0xc4, 0x85, 0x19,
	0x13, 0xb5, 0x46, 0x6d, 0xa8, 0xcc, 0x12, 0xb6, 0x24, 0x42, 0xcd, 0x47, 0xb3, 0xeb, 0xea, 0xe4,
	0x92, 0x86, 0xe7, 0x6a, 0x1f, 0x1b, 0x3f, 0x7a, 0x08, 0x8d, 0x20, 0x59, 0xa6, 0x8c, 0x72, 0x35,
	0x87, 0xe5, 0xf5, 0x5a, 0xfa, 0x2b, 0xc7, 0xe4, 0x2a, 0xa5, 0x78, 0x1d, 0x59, 0xcc, 0x40, 0x65,
	0x35, 0x03, 0x7e, 0x1f, 0xdc, 0xd7, 0x54, 0xb0, 0x30, 0xe0, 0x63, 0xca, 0x42, 0xca, 0x07, 0xf1,
	0x14, 0x35, 0x0b, 0xd6, 0xeb, 0x8a, 0xe5, 0x3b, 0xd0, 0x08, 0xf9, 0x99, 0xcc, 0x14, 0x51, 0xa1,
	0x9b, 0x56, 0xc3, 0x10, 0xf2, 0xbe, 0xd9, 0xf1, 0x9f, 0xc0, 0xae, 0x49, 0x82, 0x29, 0x4f, 0x93,
	0x98, 0xd3, 0x0f, 0x72, 0x78, 0x50, 0xe5, 0x59, 0x10, 0x50, 0xce, 0x4d, 0x7c, 0x6e, 0xfa, 0x23,
	0xd8, 0x1e, 0xd3, 0x78, 0xfa, 0xdf, 0x23, 0xe5, 0x18, 0x05, 0x49, 0x16, 0x0b, 0xc5, 0xa3, 0x83,
	0xb5, 0xe1, 0xff, 0x65, 0xc1, 0xb6, 0xa9, 0xe6, 0x38, 0x09, 0x63, 0x81, 0x3a, 0x50, 0x9a, 0x84,
	0x4b, 0x6a, 0xc6, 0xa8, 0xd5, 0xd1, 0x52, 0xd0, 0xc9, 0xa5, 0xa0, 0x33, 0xc9, 0xa5, 0x00, 0x2b,
	0x9c, 0x6c, 0xb4, 0xca, 0x44, 0x99, 0x3e, 0xb1, 0x91, 0x93, 0x6b, 0xb2, 0xf6, 0x8d, 0x13, 0x17,
	0x30, 0xf4, 0x1d, 0x54, 0xa4, 0xa0, 0xb0, 0x7c, 0xa8, 0xfe, 0xbf, 0x11, 0x30, 0x51, 0x2e, 0x6c,
	0x20, 0x12, 0x3c, 0xcf, 0xc8, 0x9c, 0x72, 0xd5, 0xe9, 0xeb, 0xe0, 0x03, 0xe5, 0xc2, 0x06, 0xe2,
	0x1f, 0x15, 0xd4, 0xe6, 0xc7, 0xca, 0xf7, 0x94, 0xa4, 0x5c, 0x5d, 0xc7, 0xc1, 0x72, 0x29, 0x1b,
	0xcb, 0xc3, 0xdf, 0x74, 0x67, 0x1c, 0xac, 0xd6, 0x72, 0xf6, 0x28, 0x63, 0x89, 0x29, 0xc9, 0xc1,
	0xc6, 0xf2, 0xdf, 0xc3, 0xce, 0x46, 0x59, 0xe8, 0x07, 0xa8, 0xe5, 0x62, 0x69, 0x28, 0xfa, 0xf2,
	0x03, 0x8a, 0xf6, 0x0d, 0x00, 0x17, 0x50, 0x74, 0x0f, 0xca, 0x22, 0x11, 0x24, 0x32, 0x14, 0x7d,
	0x22, 0x46, 0xe3, 0xfc, 0x37, 0xc5, 0xc1, 0xfa, 0x8a, 0xb2, 0x7d, 0x5c, 0x10, 0x41, 0xcd, 0x4d,
	0xb4, 0x21, 0xdb, 0xfd, 0x3e, 0x61, 0x8b, 0x9c, 0x7c, 0x07, 0xe7, 0xa6, 0xbc, 0xd1, 0x8c, 0x84,
	0x11, 0x9d, 0xaa, 0x1b, 0xd5, 0xb0, 0xb1, 0xfc, 0xc3, 0xa2, 0xdf, 0x83, 0x4b, 0x29, 0x80, 0xd7,
	0x07, 0xa8, 0x0d, 0x65, 0xe5, 0xf0, 0x9c, 0x75, 0x81, 0x58, 0x1f, 0x11, 0xac, 0x01, 0xfe, 0x3b,
	0x68, 0x68, 0x1d, 0x38, 0x91, 0x82, 0x24, 0x69, 0x55, 0xca, 0xab, 0x53, 0xa9, 0x35, 0x42, 0xe0,
	0x84, 0xb1, 0x7e, 0xcf, 0xce, 0xe1, 0x16, 0x96, 0x06, 0x72, 0xc1, 0x9e, 0x45, 0xaa, 0x28, 0xfb,
	0x70, 0x0b, 0xdb, 0xb3, 0x68, 0xfd, 0x37, 0x51, 0xd2, 0x97, 0x30, 0xe6, 0xb3, 0xaa, 0x91, 0x3e,
	0xff, 0x6f, 0x0b, 0xaa, 0x46, 0x74, 0xd0, 0x8f, 0xb0, 0x33, 0xa5, 0x33, 0x92, 0x45, 0xe2, 0x4c,
	0x92, 0x20, 0x7b, 0x2b, 0x2b, 0xfd, 0xdf, 0xba, 0x34, 0xa9, 0x92, 0xf0, 0xb6, 0xc1, 0x8d, 0x25,
	0x0c, 0xdd, 0x07, 0xc8, 0x38, 0x65, 0x26, 0xc8, 0xfe, 0x58, 0x50, 0x5d, 0x82, 0x74, 0xc4, 0x53,
	0xd8, 0x4e, 0x59, 0x22, 0x5f, 0x0f, 0x9d, 0x9e, 0x11, 0x61, 0xc6, 0xf5, 0x53, 0x6f, 0xa2, 0x51,
	0xe0, 0x7b, 0x62, 0xf5, 0xe2, 0x4a, 0x6b, 0x2f, 0xce, 0xc8, 0xb9, 0xf9, 0x7b, 0xd5, 0xb0, 0x36,
	0xee, 0x9e, 0xc0, 0xee, 0x35, 0x65, 0x44, 0x0d, 0xa8, 0xfe, 0x32, 0x7a, 0x39, 0x3a, 0x7a, 0x33,
	0x72, 0xb7, 0xa4, 0x31, 0x1e, 0x8e, 0x5e, 0x9e, 0x8d, 0x1f, 0xb8, 0x16, 0x6a, 0x02, 0x1c, 0xe3,
	0xa3, 0x17, 0x83, 0xfe, 0x44, 0xda, 0x36, 0x02, 0xa8, 0x1c, 0xe0, 0xe1, 0xfe, 0xf3, 0xb1, 0xeb,
	0xa0, 0x1d, 0xa8, 0x0f, 0x8e, 0x0f, 0x07, 0xaf, 0x07, 0xb8, 0xf7, 0xca, 0x2d, 0xdd, 0x7d, 0x0a,
	0xb0, 0x12, 0x45, 0x54, 0x83, 0xd2, 0x64, 0xf0, 0x76, 0xe2, 0x6e, 0xc9, 0xd5, 0xf3, 0xc9, 0x7e,
	0xdf, 0xb5, 0xe4, 0xea, 0xd9, 0xf8, 0x68, 0xe4, 0xda, 0x72, 0xf5, 0x42, 0xae, 0x1c, 0x54, 0x05,
	0xa7, 0x3f, 0x3e, 0x71, 0x4b, 0x77, 0x7f, 0x86, 0xdd, 0x6b, 0x22, 0x29, 0x51, 0xa3, 0xa3, 0xd1,
	0xc0, 0xdd, 0x42, 0x75, 0x28, 0x4f, 0x7a, 0xf8, 0xe0, 0xd4, 0xb5, 0x64, 0xc0, 0xe9, 0xf0, 0xd8,
	0xb5, 0x51, 0x05, 0xec, 0x83, 0x53, 0xd7, 0x91, 0xdf, 0xb7, 0xa7, 0x6e, 0xa9, 0xfb, 0xbb, 0x03,
	0xb7, 0xc6, 0x61, 0xbc, 0x38, 0xa6, 0x4c, 0x09, 0x72, 0x1c, 0x50, 0x33, 0x4b, 0xe8, 0x29, 0xa0,
	0x3e, 0xa3, 0x44, 0x98, 0x0d, 0xad, 0xa8, 0xc8, 0x5d, 0xff, 0x71, 0xc9, 0xd2, 0x5b, 0x9b, 0x7a,
	0x52, 0x28, 0xdf, 0x13, 0x70, 0x7b, 0x42, 0x90, 0xe0, 0x62, 0xed, 0x0f, 0x78, 0xe3, 0xe0, 0xc7,
	0xb0, 0xab, 0x83, 0x7b, 0xc5, 0xbf, 0xee, 0xc6, 0xb1, 0x8f, 0x60, 0xc7, 0x1c, 0x6c, 0x06, 0xf2,
	0xc6, 0x91, 0x0f, 0xa1, 0x21, 0xc5, 0x3b, 0x27, 0x60, 0xf3, 0x6d, 0xa9, 0x47, 0xd5, 0x32, 0x7b,
	0xeb, 0x1a, 0xdf, 0xb6, 0xe4, 0x20, 0xf6, 0xa3, 0x84, 0x17, 0xd4, 0xdd, 0xda, 0x88, 0x2c, 0xfe,
	0x45, 0x1f, 0x39, 0xf7, 0x19, 0x9c, 0xd6, 0x42, 0xa9, 0x86, 0x31, 0x89, 0xce, 0x2b, 0x6a, 0x6a,
	0x1f, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xe4, 0x33, 0xa4, 0x16, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SinkPerformanceMetricsClient is the client API for SinkPerformanceMetrics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SinkPerformanceMetricsClient interface {
	CreateMetricSeries(ctx context.Context, in *ResultData, opts ...grpc.CallOption) (*MetricsResponse, error)
	AttachResultData(ctx context.Context, in *ResultData, opts ...grpc.CallOption) (*MetricsResponse, error)
	AttachArtifacts(ctx context.Context, in *ResultData, opts ...grpc.CallOption) (*MetricsResponse, error)
	AttachRollups(ctx context.Context, in *ResultData, opts ...grpc.CallOption) (*MetricsResponse, error)
	SendMetrics(ctx context.Context, opts ...grpc.CallOption) (SinkPerformanceMetrics_SendMetricsClient, error)
	CloseMetrics(ctx context.Context, in *MetricsSeriesEnd, opts ...grpc.CallOption) (*MetricsResponse, error)
}

type sinkPerformanceMetricsClient struct {
	cc *grpc.ClientConn
}

func NewSinkPerformanceMetricsClient(cc *grpc.ClientConn) SinkPerformanceMetricsClient {
	return &sinkPerformanceMetricsClient{cc}
}

func (c *sinkPerformanceMetricsClient) CreateMetricSeries(ctx context.Context, in *ResultData, opts ...grpc.CallOption) (*MetricsResponse, error) {
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, "/sink.SinkPerformanceMetrics/CreateMetricSeries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sinkPerformanceMetricsClient) AttachResultData(ctx context.Context, in *ResultData, opts ...grpc.CallOption) (*MetricsResponse, error) {
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, "/sink.SinkPerformanceMetrics/AttachResultData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sinkPerformanceMetricsClient) AttachArtifacts(ctx context.Context, in *ResultData, opts ...grpc.CallOption) (*MetricsResponse, error) {
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, "/sink.SinkPerformanceMetrics/AttachArtifacts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sinkPerformanceMetricsClient) AttachRollups(ctx context.Context, in *ResultData, opts ...grpc.CallOption) (*MetricsResponse, error) {
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, "/sink.SinkPerformanceMetrics/AttachRollups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sinkPerformanceMetricsClient) SendMetrics(ctx context.Context, opts ...grpc.CallOption) (SinkPerformanceMetrics_SendMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SinkPerformanceMetrics_serviceDesc.Streams[0], "/sink.SinkPerformanceMetrics/SendMetrics", opts...)
	if err != nil {
		return nil, err
	}
	x := &sinkPerformanceMetricsSendMetricsClient{stream}
	return x, nil
}

type SinkPerformanceMetrics_SendMetricsClient interface {
	Send(*MetricsEvent) error
	CloseAndRecv() (*SendResponse, error)
	grpc.ClientStream
}

type sinkPerformanceMetricsSendMetricsClient struct {
	grpc.ClientStream
}

func (x *sinkPerformanceMetricsSendMetricsClient) Send(m *MetricsEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sinkPerformanceMetricsSendMetricsClient) CloseAndRecv() (*SendResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SendResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sinkPerformanceMetricsClient) CloseMetrics(ctx context.Context, in *MetricsSeriesEnd, opts ...grpc.CallOption) (*MetricsResponse, error) {
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, "/sink.SinkPerformanceMetrics/CloseMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SinkPerformanceMetricsServer is the server API for SinkPerformanceMetrics service.
type SinkPerformanceMetricsServer interface {
	CreateMetricSeries(context.Context, *ResultData) (*MetricsResponse, error)
	AttachResultData(context.Context, *ResultData) (*MetricsResponse, error)
	AttachArtifacts(context.Context, *ResultData) (*MetricsResponse, error)
	AttachRollups(context.Context, *ResultData) (*MetricsResponse, error)
	SendMetrics(SinkPerformanceMetrics_SendMetricsServer) error
	CloseMetrics(context.Context, *MetricsSeriesEnd) (*MetricsResponse, error)
}

func RegisterSinkPerformanceMetricsServer(s *grpc.Server, srv SinkPerformanceMetricsServer) {
	s.RegisterService(&_SinkPerformanceMetrics_serviceDesc, srv)
}

func _SinkPerformanceMetrics_CreateMetricSeries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResultData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinkPerformanceMetricsServer).CreateMetricSeries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sink.SinkPerformanceMetrics/CreateMetricSeries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinkPerformanceMetricsServer).CreateMetricSeries(ctx, req.(*ResultData))
	}
	return interceptor(ctx, in, info, handler)
}

func _SinkPerformanceMetrics_AttachResultData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResultData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinkPerformanceMetricsServer).AttachResultData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sink.SinkPerformanceMetrics/AttachResultData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinkPerformanceMetricsServer).AttachResultData(ctx, req.(*ResultData))
	}
	return interceptor(ctx, in, info, handler)
}

func _SinkPerformanceMetrics_AttachArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResultData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinkPerformanceMetricsServer).AttachArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sink.SinkPerformanceMetrics/AttachArtifacts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinkPerformanceMetricsServer).AttachArtifacts(ctx, req.(*ResultData))
	}
	return interceptor(ctx, in, info, handler)
}

func _SinkPerformanceMetrics_AttachRollups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResultData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinkPerformanceMetricsServer).AttachRollups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sink.SinkPerformanceMetrics/AttachRollups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinkPerformanceMetricsServer).AttachRollups(ctx, req.(*ResultData))
	}
	return interceptor(ctx, in, info, handler)
}

func _SinkPerformanceMetrics_SendMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SinkPerformanceMetricsServer).SendMetrics(&sinkPerformanceMetricsSendMetricsServer{stream})
}

type SinkPerformanceMetrics_SendMetricsServer interface {
	SendAndClose(*SendResponse) error
	Recv() (*MetricsEvent, error)
	grpc.ServerStream
}

type sinkPerformanceMetricsSendMetricsServer struct {
	grpc.ServerStream
}

func (x *sinkPerformanceMetricsSendMetricsServer) SendAndClose(m *SendResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sinkPerformanceMetricsSendMetricsServer) Recv() (*MetricsEvent, error) {
	m := new(MetricsEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SinkPerformanceMetrics_CloseMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsSeriesEnd)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinkPerformanceMetricsServer).CloseMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sink.SinkPerformanceMetrics/CloseMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinkPerformanceMetricsServer).CloseMetrics(ctx, req.(*MetricsSeriesEnd))
	}
	return interceptor(ctx, in, info, handler)
}

var _SinkPerformanceMetrics_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sink.SinkPerformanceMetrics",
	HandlerType: (*SinkPerformanceMetricsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMetricSeries",
			Handler:    _SinkPerformanceMetrics_CreateMetricSeries_Handler,
		},
		{
			MethodName: "AttachResultData",
			Handler:    _SinkPerformanceMetrics_AttachResultData_Handler,
		},
		{
			MethodName: "AttachArtifacts",
			Handler:    _SinkPerformanceMetrics_AttachArtifacts_Handler,
		},
		{
			MethodName: "AttachRollups",
			Handler:    _SinkPerformanceMetrics_AttachRollups_Handler,
		},
		{
			MethodName: "CloseMetrics",
			Handler:    _SinkPerformanceMetrics_CloseMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendMetrics",
			Handler:       _SinkPerformanceMetrics_SendMetrics_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "perf.proto",
}
